// Auto-generated from Test Game spec. Run `bun run codegen` to regenerate.
// Do not edit this file manually.
import { executeRoll } from '@randsum/gameSchema'
import type { GameRollResult, RollRecord } from '@randsum/gameSchema'

export type RollResult = 'high' | 'low'

export function roll(count?: number): GameRollResult<RollResult, undefined, RollRecord>
export function roll(input?: { count?: number }): GameRollResult<RollResult, undefined, RollRecord>
export function roll(
  rawInput?: number | { count?: number }
): GameRollResult<RollResult, undefined, RollRecord> {
  const input: { count?: number } =
    typeof rawInput === 'number' ? { count: rawInput } : (rawInput ?? {})
  const r = executeRoll({
    sides: 6,
    quantity: input?.count ?? 1,
    modifiers: { keep: { highest: 1 } }
  })
  const total = r.total
  if (total === 6) return { total, result: 'high', rolls: r.rolls }
  if (total >= 1 && total <= 5) return { total, result: 'low', rolls: r.rolls }
  throw new Error(`No table match for total ${total}`)
}

export type RollBonusResult = 'done'

export function rollBonus(sides?: number): GameRollResult<RollBonusResult, undefined, RollRecord>
export function rollBonus(input?: {
  sides?: number
}): GameRollResult<RollBonusResult, undefined, RollRecord>
export function rollBonus(
  rawInput?: number | { sides?: number }
): GameRollResult<RollBonusResult, undefined, RollRecord> {
  const input: { sides?: number } =
    typeof rawInput === 'number' ? { sides: rawInput } : (rawInput ?? {})
  const r = executeRoll({ sides: input?.sides ?? 6, quantity: 1 })
  const total = r.total
  if (total >= 1 && total <= 20) return { total, result: 'done', rolls: r.rolls }
  throw new Error(`No table match for total ${total}`)
}

export type { GameRollResult, RollRecord }
