[build]
  base = "."
  command = "bun run --filter @randsum/roller build && bun run --filter @randsum/rdn build"
  publish = "apps/rdn/dist"

[dev]
  command = "astro dev"
  targetPort = 4322
  port = 8889
