/* eslint-disable */
// Auto-generated from Daggerheart spec. Run `bun run codegen` to regenerate.
// Do not edit this file manually.
import { executeRoll, validateFinite, validateRange } from '@randsum/gameSchema'
import type { GameRollResult, RollRecord } from '@randsum/gameSchema'

export type RollResult = 'critical hope' | 'fear' | 'hope'

export interface RollDetails {
  readonly hope: { readonly roll: number; readonly amplified: boolean }
  readonly fear: { readonly roll: number; readonly amplified: boolean }
  readonly modifier: number
  readonly extraDie:
    | { readonly advantageRoll: number; readonly disadvantageRoll: number }
    | undefined
}

export function roll(input?: {
  modifier?: number
  amplifyHope?: boolean
  amplifyFear?: boolean
  rollingWith?: 'Advantage' | 'Disadvantage'
}): GameRollResult<RollResult, RollDetails, RollRecord> {
  if (input?.modifier !== undefined && typeof input?.modifier === 'number')
    validateFinite(input?.modifier, 'Daggerheart modifier')
  if (input?.modifier !== undefined && typeof input?.modifier === 'number')
    validateRange(input?.modifier, -30, 30, 'Daggerheart modifier')
  if (
    input?.rollingWith !== undefined &&
    !['Advantage', 'Disadvantage'].includes(input?.rollingWith as string)
  )
    throw new Error(
      `Invalid rollingWith value: ${String(input?.rollingWith)}. Must be 'Advantage' or 'Disadvantage'.`
    )
  const hopeResult = executeRoll({ sides: input?.amplifyHope ? 20 : 12, quantity: 1 })
  const hopeTotal = hopeResult.rolls.flatMap(r => r.rolls).reduce((s, v) => s + v, 0)
  const fearResult = executeRoll({ sides: input?.amplifyFear ? 20 : 12, quantity: 1 })
  const fearTotal = fearResult.rolls.flatMap(r => r.rolls).reduce((s, v) => s + v, 0)
  const rolls: RollRecord[] = [...hopeResult.rolls, ...fearResult.rolls]
  let total = hopeTotal + fearTotal
  let conditionalPool0Total = 0
  let conditionalPool1Total = 0
  if (input?.rollingWith === 'Advantage') {
    const cpResult = executeRoll({ sides: 6, quantity: 1 })
    const cpTotal = cpResult.rolls.flatMap(r => r.rolls).reduce((s, v) => s + v, 0)
    conditionalPool0Total = cpTotal
    total += cpTotal
    rolls.push(...cpResult.rolls)
  }
  if (input?.rollingWith === 'Disadvantage') {
    const cpResult = executeRoll({ sides: 6, quantity: 1 })
    const cpTotal = cpResult.rolls.flatMap(r => r.rolls).reduce((s, v) => s + v, 0)
    conditionalPool1Total = cpTotal
    total -= cpTotal
    rolls.push(...cpResult.rolls)
  }
  total += input?.modifier ?? 0
  const details = {
    hope: { roll: hopeTotal, amplified: input?.amplifyHope ?? false },
    fear: { roll: fearTotal, amplified: input?.amplifyFear ?? false },
    modifier: input?.modifier ?? 0,
    extraDie:
      input?.rollingWith !== undefined
        ? { advantageRoll: conditionalPool0Total, disadvantageRoll: conditionalPool1Total }
        : undefined
  }
  if (hopeTotal === fearTotal) return { total, result: 'critical hope', rolls, details }
  if (hopeTotal > fearTotal) return { total, result: 'hope', rolls, details }
  return { total, result: 'fear', rolls, details }
}

export type { GameRollResult, RollRecord }
