import { SchemaError } from './errors'
import type { NormalizedRollDefinition, NormalizedSpec } from './normalizedTypes'
import { normalizeSpec } from './normalizer'
import type { RandSumSpec, RemoteTableLookupOperation, ResultMappingLeaf } from './types'
import { validateSpec } from './validator'
import { generateRollParts } from './codegen/emitBody'
import { needsValidationImports, specToFilename } from './codegen/emitHelpers'

async function fetchRemoteData(url: string, dataPath?: string): Promise<unknown[]> {
  const response = await fetch(url)
  if (!response.ok) {
    throw new SchemaError(
      `Failed to fetch remote table data from ${url}: ${String(response.status)}`,
      'INVALID_SPEC'
    )
  }
  const json: unknown = await response.json()
  if (dataPath === undefined) return json as unknown[]
  const traversed = dataPath
    .split('.')
    .reduce((acc: unknown, part: string) => (acc as Record<string, unknown>)[part], json)
  return traversed as unknown[]
}

export interface GenerateCodeOptions {
  readonly remoteDataCache?: ReadonlyMap<string, readonly unknown[]>
}

/**
 * Recursively collect top-level field names referenced by `$foundTable`
 * in a result mapping leaf (including fallbacks).
 */
function collectFoundTableFields(leaf: ResultMappingLeaf, fields: Set<string>): void {
  if ('$foundTable' in leaf) {
    const topLevel = leaf.$foundTable.split('.')[0]
    if (topLevel !== undefined) fields.add(topLevel)
  }
  if ('$lookupResult' in leaf && leaf.fallback !== undefined) {
    collectFoundTableFields(leaf.fallback, fields)
  }
}

/**
 * Derive the set of top-level field names that the generated code actually
 * accesses from each remote data entry. Derived from the spec's `find.field`,
 * `tableField`, and any `$foundTable` references in `resultMapping`.
 * The `name` field is always included because `VALID_TABLE_NAMES` reads it
 * from every entry.
 */
function collectRequiredRemoteFields(rtl: RemoteTableLookupOperation): ReadonlySet<string> {
  const fields = new Set<string>(['name', rtl.find.field, rtl.tableField])
  for (const leaf of Object.values(rtl.resultMapping)) {
    collectFoundTableFields(leaf, fields)
  }
  return fields
}

/**
 * Strip each remote data entry down to only the fields the generated code
 * needs, removing metadata that would otherwise bloat the output.
 */
function stripRemoteEntries(
  data: readonly unknown[],
  requiredFields: ReadonlySet<string>
): unknown[] {
  return data.map(entry => {
    if (typeof entry !== 'object' || entry === null) return entry
    const source = entry as Record<string, unknown>
    const stripped: Record<string, unknown> = {}
    for (const field of requiredFields) {
      if (field in source) {
        stripped[field] = source[field]
      }
    }
    return stripped
  })
}

async function buildCodeString(
  nspec: NormalizedSpec,
  options?: GenerateCodeOptions
): Promise<string> {
  // Detect remoteTableLookup and fetch data at codegen time
  const rtlDef = Object.values(nspec.rolls).find(
    (
      rollDef
    ): rollDef is NormalizedRollDefinition & {
      resolve: { readonly remoteTableLookup: RemoteTableLookupOperation }
    } => typeof rollDef.resolve === 'object' && 'remoteTableLookup' in rollDef.resolve
  )?.resolve.remoteTableLookup
  const remoteData: unknown[] | undefined = rtlDef
    ? ((options?.remoteDataCache?.get(rtlDef.url) as unknown[] | undefined) ??
      (await fetchRemoteData(rtlDef.url, rtlDef.dataPath)))
    : undefined

  const { needsFinite, needsRange } = needsValidationImports(nspec)
  const validationImports: string[] = []
  if (needsFinite) validationImports.push('validateFinite')
  if (needsRange) validationImports.push('validateRange')
  const hasRemote = remoteData !== undefined
  const parts: string[] = [
    `/* eslint-disable */`,
    `// Auto-generated from ${nspec.name} spec. Run \`bun run codegen\` to regenerate.`,
    `// Do not edit this file manually.`,
    `import { roll as executeRoll } from '@randsum/roller/roll'`,
    ...(validationImports.length > 0
      ? [`import { ${validationImports.join(', ')} } from '@randsum/roller/validate'`]
      : []),
    `import type { RollRecord } from '@randsum/roller'`,
    `import type { GameRollResult } from './types'`,
    `import { SchemaError } from './lib/errors'`,
    `import type { SchemaErrorCode } from './lib/errors'`
  ]

  if (hasRemote) {
    parts.push(`import { lookupByRange } from './lib/lookupByRange'`)
  }

  parts.push(``)

  if (remoteData !== undefined && rtlDef !== undefined) {
    const strippedData = stripRemoteEntries(remoteData, collectRequiredRemoteFields(rtlDef))
    parts.push(`const REMOTE_DATA = ${JSON.stringify(strippedData)} as const`)
    parts.push(``)
  }

  for (const [key, rollDef] of Object.entries(nspec.rolls)) {
    parts.push(...generateRollParts(key, rollDef, nspec.name, nspec.shortcode))
  }

  parts.push(`export { SchemaError }`)
  parts.push(`export type { GameRollResult, RollRecord, SchemaErrorCode }`)

  if (remoteData !== undefined) {
    parts.push(``)
    parts.push(`export const ROLL_TABLE_ENTRIES: typeof REMOTE_DATA = REMOTE_DATA`)
    const tableNames = remoteData
      .map(entry => (entry as Record<string, unknown>)['name'] as string)
      .filter((name): name is string => typeof name === 'string')
    const namesLiteral = tableNames
      .map(n => `  '${n.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`)
      .join(',\n')
    parts.push(`export const VALID_TABLE_NAMES = [\n${namesLiteral}\n] as const`)
  }

  parts.push(``)

  return parts.join('\n')
}

/**
 * Generate TypeScript roll functions from a spec.
 *
 * @param spec - The parsed .randsum.json spec
 */
export async function generateCode(
  spec: RandSumSpec,
  options?: GenerateCodeOptions
): Promise<string> {
  const result = validateSpec(spec)
  if (!result.valid) {
    const summary = result.errors.map(e => `${e.path}: ${e.message}`).join('; ')
    throw new SchemaError(`Invalid spec: ${summary}`, 'INVALID_SPEC')
  }

  const nspec = normalizeSpec(spec)
  return buildCodeString(nspec, options)
}

export { specToFilename }
