export * from './isD'
export * from './isRollResult'
export * from './isDiceNotation'
export * from './isNumericRollOptions'
export * from './isNumericRollParams'
export * from './isCustomRollParams'
