[test]
coverage = false
coverageReporter = ['text', 'lcov']
coverageThreshold = { lines = 95.0, functions = 95.0, branches = 90.0, statements = 95.0 }
coverageDirectory = "coverage"
coverageIgnorePatterns = [
  "node_modules/",
  "dist/",
  "**/*.d.ts",
  "**/*.test.ts",
  "**/*.spec.ts",
  "**/test/**",
  "**/__tests__/**",
  "**/coverage/**"
]
