# Monorepo Workspace Configuration
[workspace]
# Define workspace patterns
patterns = ["packages/*"]
# Exclude patterns
exclude = ["**/dist", "**/node_modules", "**/.git"]
# Hoist common dependencies
hoist = true
# Shared cache for all workspace packages
sharedCache = true
# Dependency version resolution strategy
resolutionStrategy = "highest"

# Test Configuration
[test]
# Coverage settings
coverage = true
coverageReporter = ['text', 'lcov']
coverageThreshold = { lines = 1.0, functions = 0.0, branches = 0.8, statements = 0.8 }
coverageDirectory = "coverage"
coverageIgnorePatterns = [
  "node_modules/",
  "dist/",
  ".*.mjs",
  "**/*.d.ts",
  "**/*.test.ts",
  "**/test/**"
]

# Monorepo-specific test settings
workspaceTestTimeout = 10000
parallelTests = true
maxWorkers = "70%"

# Test execution settings
testTimeout = 5000
testPathIgnorePatterns = [
  "node_modules/",
  "dist/"
]
testMatch = ["**/__tests__/**/*.[jt]s?(x)", "**/?(*.)+(spec|test).[jt]s?(x)"]

# Test environment settings
env = { NODE_ENV = "test" }
setupFiles = ["./test/setup.ts"]

# Debug settings
logHeapUsage = true
detectLeaks = true
detectOpenHandles = true

[install]
# Package management settings
production = false
frozen = true
registry = "https://registry.npmjs.org/"
cache = ".bun-cache"

# Monorepo-specific install settings
workspaceRoot = "."
lockfile = true
preferOffline = true
noDuplicates = true
pruneDevDependencies = true

[dependencies]
# Dependency management for monorepo
checkForDuplicates = true
strictPeerDependencies = true
autoInstall = true
preferWorkspacePackages = true

[debug]
# Debug settings for development
profile = true
breakOnFirstLine = false
showAllWarnings = true
logLevel = "info"

# Monorepo-specific debug settings
workspaceDebug = true
crossPackageSourceMaps = true

[compile]
# Compilation settings
sourcemap = true
minify = false
target = "node"
splitting = true
outDir = "dist"
entrypoints = ["src/index.ts"]

# Monorepo-specific compile settings
workspaceReferences = true
preserveModules = true
declaration = true
composite = true
incremental = true

[watch]
# Watch mode settings
ignore = [
  "**/node_modules/**",
  "**/dist/**",
  "**/.git/**",
  "**/coverage/**"
]
extensions = [".ts", ".tsx", ".js", ".jsx", ".json"]

# Monorepo-specific watch settings
watchDependencies = true
aggregateTimeout = 300
poll = 1000

[build]
# Build settings
minify = true
sourcemap = true
target = ["node22", "bun1"]
outDir = "dist"
splitting = true
publicPath = "/"

# Monorepo-specific build settings
workspaceDependencies = true
buildOrder = "parallel"
maxConcurrentBuilds = 4
incrementalBuild = true
cacheEnabled = true
cacheDirectory = ".build-cache"

[monorepo]
# Package management
enforceConsistentDependencies = true
enforceConsistentVersions = true
sharedDependencies = [
  "typescript",
  "@types/*",
  "bunup"
]

# Build optimization
buildConcurrency = 4
buildCache = true
buildCacheLocation = ".build-cache"

# Dependency management
hoistingLimits = "workspaces"
nohoist = [
  "**/react-native",
  "**/react-native/**"
]

# Publishing
publishConfig = { access = "public" }
versionStrategy = "independent"

[performance]
# Memory management
gcInterval = "100mb"
maxOldSpaceSize = 4096

# Build optimization
optimizeDeps = true
esbuildMinify = true
terserMinify = false

# Cache settings
cacheDirectory = ".cache"
persistentCache = true
hardSourceCache = true

[security]
# Package security
allowedPublishRegistries = ["https://registry.npmjs.org/"]
enforceHttps = true
checkVulnerabilities = true
