// This file is generated by codegen.ts — do not edit by hand.
export const AVAILABLE_GAMES = [
  'blades',
  'daggerheart',
  'fifth',
  'pbta',
  'root-rpg',
  'salvageunion'
] as const

export type GameShortcode = (typeof AVAILABLE_GAMES)[number]
