// Auto-generated from Blades in the Dark spec. Run `bun run codegen` to regenerate.
// Do not edit this file manually.
import { roll as executeRoll } from '@randsum/roller/roll'
import { validateFinite, validateRange } from '@randsum/roller/validate'
import type { RollRecord } from '@randsum/roller'
import type { GameRollResult } from './types'
import { SchemaError } from './lib/errors'
import type { SchemaErrorCode } from './lib/errors'

export type BladesRollResult = 'critical' | 'failure' | 'partial' | 'success'

export function roll(rating?: number): GameRollResult<BladesRollResult, undefined, RollRecord>
export function roll(input?: {
  rating?: number
}): GameRollResult<BladesRollResult, undefined, RollRecord>
export function roll(
  rawInput?: number | { rating?: number }
): GameRollResult<BladesRollResult, undefined, RollRecord> {
  const input: { rating?: number } =
    typeof rawInput === 'number' ? { rating: rawInput } : (rawInput ?? {})
  if (input?.rating !== undefined && typeof input?.rating === 'number')
    validateFinite(
      input?.rating,
      'Dice pool size including action rating, assists, and push (0 = desperate, 1-6 = standard)'
    )
  if (input?.rating !== undefined && typeof input?.rating === 'number')
    validateRange(
      input?.rating,
      0,
      6,
      'Dice pool size including action rating, assists, and push (0 = desperate, 1-6 = standard)'
    )
  if (input?.rating === 0) {
    const r = executeRoll({ sides: 6, quantity: 2, modifiers: { keep: { lowest: 1 } } })
    const total = r.total
    if (total === 6) return { total, result: 'success', rolls: r.rolls }
    if (total >= 4 && total <= 5) return { total, result: 'partial', rolls: r.rolls }
    if (total >= 1 && total <= 3) return { total, result: 'failure', rolls: r.rolls }
    throw new SchemaError(`No table entry matches total ${total}`, 'NO_TABLE_MATCH')
  }
  const r = executeRoll({
    sides: 6,
    quantity: input?.rating ?? 1,
    modifiers: { keep: { highest: 1 } }
  })
  const preModify = r.rolls.flatMap(x => x.initialRolls)
  const total = r.total
  if (preModify.filter(v => v === 6).length >= 2)
    return { total, result: 'critical', rolls: r.rolls }
  if (total === 6) return { total, result: 'success', rolls: r.rolls }
  if (total >= 4 && total <= 5) return { total, result: 'partial', rolls: r.rolls }
  if (total >= 1 && total <= 3) return { total, result: 'failure', rolls: r.rolls }
  throw new SchemaError(`No table entry matches total ${total}`, 'NO_TABLE_MATCH')
}

export { SchemaError }
export type { GameRollResult, RollRecord, SchemaErrorCode }
