/* eslint-disable */
// Auto-generated from Daggerheart spec. Run `bun run codegen` to regenerate.
// Do not edit this file manually.
import { roll as executeRoll } from '@randsum/roller/roll'
import { validateFinite, validateRange } from '@randsum/roller/validate'
import type { RollRecord } from '@randsum/roller/types'
import type { GameRollResult } from './types'
import { SchemaError } from './lib/errors'
import type { SchemaErrorCode } from './lib/errors'

export type DaggerheartRollResult = 'critical hope' | 'fear' | 'hope'

export interface DaggerheartRollDetails {
  readonly hope: { readonly roll: number; readonly amplified: boolean }
  readonly fear: { readonly roll: number; readonly amplified: boolean }
  readonly modifier: number
  readonly extraDie:
    | { readonly advantageRoll: number; readonly disadvantageRoll: number }
    | undefined
}

export function roll(input?: {
  modifier?: number
  amplifyHope?: boolean
  amplifyFear?: boolean
  rollingWith?: 'Advantage' | 'Disadvantage'
}): GameRollResult<DaggerheartRollResult, DaggerheartRollDetails, RollRecord> {
  if (input?.modifier !== undefined && typeof input?.modifier === 'number')
    validateFinite(input?.modifier, 'Daggerheart modifier')
  if (input?.modifier !== undefined && typeof input?.modifier === 'number')
    validateRange(input?.modifier, -30, 30, 'Daggerheart modifier')
  if (
    input?.rollingWith !== undefined &&
    !['Advantage', 'Disadvantage'].includes(input?.rollingWith as string)
  )
    throw new SchemaError(
      'INVALID_INPUT_TYPE',
      `Invalid rollingWith value: ${String(input?.rollingWith)}. Must be 'Advantage' or 'Disadvantage'.`
    )
  const hopeResult = executeRoll({ sides: input?.amplifyHope ? 20 : 12, quantity: 1 })
  const hopeTotal = hopeResult.rolls.flatMap(r => r.rolls).reduce((s, v) => s + v, 0)
  const fearResult = executeRoll({ sides: input?.amplifyFear ? 20 : 12, quantity: 1 })
  const fearTotal = fearResult.rolls.flatMap(r => r.rolls).reduce((s, v) => s + v, 0)
  const rolls: RollRecord[] = [...hopeResult.rolls, ...fearResult.rolls]
  let total = hopeTotal + fearTotal
  let conditionalPool_advantageTotal = 0
  let conditionalPool_disadvantageTotal = 0
  if (input?.rollingWith === 'Advantage') {
    const cpResult = executeRoll({ sides: 6, quantity: 1 })
    const cpTotal = cpResult.rolls.flatMap(r => r.rolls).reduce((s, v) => s + v, 0)
    conditionalPool_advantageTotal = cpTotal
    total += cpTotal
    rolls.push(...cpResult.rolls)
  }
  if (input?.rollingWith === 'Disadvantage') {
    const cpResult = executeRoll({ sides: 6, quantity: 1 })
    const cpTotal = cpResult.rolls.flatMap(r => r.rolls).reduce((s, v) => s + v, 0)
    conditionalPool_disadvantageTotal = cpTotal
    total -= cpTotal
    rolls.push(...cpResult.rolls)
  }
  total += input?.modifier ?? 0
  const details = {
    hope: { roll: hopeTotal, amplified: input?.amplifyHope ?? false },
    fear: { roll: fearTotal, amplified: input?.amplifyFear ?? false },
    modifier: input?.modifier ?? 0,
    extraDie:
      input?.rollingWith !== undefined
        ? {
            advantageRoll: conditionalPool_advantageTotal,
            disadvantageRoll: conditionalPool_disadvantageTotal
          }
        : undefined
  }
  if (hopeTotal === fearTotal) return { total, result: 'critical hope', rolls, details }
  if (hopeTotal > fearTotal) return { total, result: 'hope', rolls, details }
  return { total, result: 'fear', rolls, details }
}

export { SchemaError }
export type { GameRollResult, RollRecord, SchemaErrorCode }
