// Auto-generated from Fate Core spec. Run `bun run codegen` to regenerate.
// Do not edit this file manually.
import { roll as executeRoll } from '@randsum/roller/roll'
import { validateFinite, validateRange } from '@randsum/roller/validate'
import type { RollRecord } from '@randsum/roller'
import type { GameRollResult } from './types'
import { SchemaError } from './lib/errors'
import type { SchemaErrorCode } from './lib/errors'

export type FateRollResult =
  | 'Abysmal'
  | 'Average'
  | 'Catastrophic'
  | 'Epic'
  | 'Fair'
  | 'Fantastic'
  | 'Good'
  | 'Great'
  | 'Legendary'
  | 'Mediocre'
  | 'Poor'
  | 'Superb'
  | 'Terrible'

export function roll(modifier?: number): GameRollResult<FateRollResult, undefined, RollRecord>
export function roll(input?: {
  modifier?: number
}): GameRollResult<FateRollResult, undefined, RollRecord>
export function roll(
  rawInput?: number | { modifier?: number }
): GameRollResult<FateRollResult, undefined, RollRecord> {
  const input: { modifier?: number } =
    typeof rawInput === 'number' ? { modifier: rawInput } : (rawInput ?? {})
  if (input?.modifier !== undefined && typeof input?.modifier === 'number')
    validateFinite(input?.modifier, 'Skill rating (Fate ladder rung) added to the 4dF total')
  if (input?.modifier !== undefined && typeof input?.modifier === 'number')
    validateRange(input?.modifier, -2, 4, 'Skill rating (Fate ladder rung) added to the 4dF total')
  const r = executeRoll(`${4}d{-1,0,1}`)
  const total = r.total + (input?.modifier ?? 0)
  if (total >= 8) return { total, result: 'Legendary', rolls: r.rolls }
  if (total === 7) return { total, result: 'Epic', rolls: r.rolls }
  if (total === 6) return { total, result: 'Fantastic', rolls: r.rolls }
  if (total === 5) return { total, result: 'Superb', rolls: r.rolls }
  if (total === 4) return { total, result: 'Great', rolls: r.rolls }
  if (total === 3) return { total, result: 'Good', rolls: r.rolls }
  if (total === 2) return { total, result: 'Fair', rolls: r.rolls }
  if (total === 1) return { total, result: 'Average', rolls: r.rolls }
  if (total === 0) return { total, result: 'Mediocre', rolls: r.rolls }
  if (total === -1) return { total, result: 'Poor', rolls: r.rolls }
  if (total === -2) return { total, result: 'Terrible', rolls: r.rolls }
  if (total === -3) return { total, result: 'Catastrophic', rolls: r.rolls }
  if (total <= -4) return { total, result: 'Abysmal', rolls: r.rolls }
  throw new SchemaError(`No table entry matches total ${total}`, 'NO_TABLE_MATCH')
}

export { SchemaError }
export type { GameRollResult, RollRecord, SchemaErrorCode }
