// Auto-generated from Fate Core spec. Run `bun run codegen` to regenerate.
// Do not edit this file manually.
import { roll as executeRoll } from '@randsum/roller/roll'
import { validateFinite, validateRange } from '@randsum/roller/validate'
import type { RollRecord } from '@randsum/roller'
import type { GameRollResult } from './types'
import { SchemaError } from './lib/errors'
import type { SchemaErrorCode } from './lib/errors'

export type FateRollResult =
  | 'average'
  | 'epic'
  | 'fair'
  | 'fantastic'
  | 'good'
  | 'great'
  | 'legendary'
  | 'mediocre'
  | 'poor'
  | 'superb'
  | 'terrible'

export function roll(modifier?: number): GameRollResult<FateRollResult, undefined, RollRecord>
export function roll(input?: {
  modifier?: number
}): GameRollResult<FateRollResult, undefined, RollRecord>
export function roll(
  rawInput?: number | { modifier?: number }
): GameRollResult<FateRollResult, undefined, RollRecord> {
  const input: { modifier?: number } =
    typeof rawInput === 'number' ? { modifier: rawInput } : (rawInput ?? {})
  if (input?.modifier !== undefined && typeof input?.modifier === 'number')
    validateFinite(
      input?.modifier,
      'Skill rating (Fate ladder rung, Terrible -2 to Superb +5) added to the 4dF total'
    )
  if (input?.modifier !== undefined && typeof input?.modifier === 'number')
    validateRange(
      input?.modifier,
      -2,
      5,
      'Skill rating (Fate ladder rung, Terrible -2 to Superb +5) added to the 4dF total'
    )
  const r = executeRoll(`${4}d{-1,0,1}`)
  const total = r.total + (input?.modifier ?? 0)
  if (total >= 8) return { total, result: 'legendary', rolls: r.rolls }
  if (total === 7) return { total, result: 'epic', rolls: r.rolls }
  if (total === 6) return { total, result: 'fantastic', rolls: r.rolls }
  if (total === 5) return { total, result: 'superb', rolls: r.rolls }
  if (total === 4) return { total, result: 'great', rolls: r.rolls }
  if (total === 3) return { total, result: 'good', rolls: r.rolls }
  if (total === 2) return { total, result: 'fair', rolls: r.rolls }
  if (total === 1) return { total, result: 'average', rolls: r.rolls }
  if (total === 0) return { total, result: 'mediocre', rolls: r.rolls }
  if (total === -1) return { total, result: 'poor', rolls: r.rolls }
  if (total <= -2) return { total, result: 'terrible', rolls: r.rolls }
  throw new SchemaError(`No table entry matches total ${total}`, 'NO_TABLE_MATCH')
}

export { SchemaError }
export type { GameRollResult, RollRecord, SchemaErrorCode }
