/* eslint-disable */
// Auto-generated from D&D 5th Edition spec. Run `bun run codegen` to regenerate.
// Do not edit this file manually.
import { roll as executeRoll, validateFinite, validateRange } from '@randsum/roller'
import type { RollRecord } from '@randsum/roller'
import type { GameRollResult } from './types'

export type RollResult = number

export function roll(input?: {
  modifier?: number
  rollingWith?: 'Advantage' | 'Disadvantage'
}): GameRollResult<RollResult, undefined, RollRecord> {
  if (input?.modifier !== undefined && typeof input?.modifier === 'number')
    validateFinite(input?.modifier, '5E modifier')
  if (input?.modifier !== undefined && typeof input?.modifier === 'number')
    validateRange(input?.modifier, -30, 30, '5E modifier')
  if (
    input?.rollingWith !== undefined &&
    !['Advantage', 'Disadvantage'].includes(input?.rollingWith as string)
  )
    throw new Error(
      `Invalid rollingWith value: ${String(input?.rollingWith)}. Must be 'Advantage' or 'Disadvantage'.`
    )
  if (input?.rollingWith === 'Advantage') {
    const r = executeRoll({
      sides: 20,
      quantity: 2,
      modifiers: { keep: { highest: 1 }, plus: input?.modifier ?? 0 }
    })
    const total = r.total
    return { total, result: total, rolls: r.rolls }
  }
  if (input?.rollingWith === 'Disadvantage') {
    const r = executeRoll({
      sides: 20,
      quantity: 2,
      modifiers: { keep: { lowest: 1 }, plus: input?.modifier ?? 0 }
    })
    const total = r.total
    return { total, result: total, rolls: r.rolls }
  }
  const r = executeRoll({ sides: 20, quantity: 1, modifiers: { plus: input?.modifier ?? 0 } })
  const total = r.total
  return { total, result: total, rolls: r.rolls }
}

export type { GameRollResult, RollRecord }
