// Auto-generated from D&D 5th Edition spec. Run `bun run codegen` to regenerate.
// Do not edit this file manually.
import { roll as executeRoll } from '@randsum/roller/roll'
import { validateFinite, validateRange } from '@randsum/roller/validate'
import type { RollRecord } from '@randsum/roller'
import type { GameRollResult } from './types'
import { SchemaError } from './lib/errors'
import type { SchemaErrorCode } from './lib/errors'

export type FifthRollResult = number

export interface FifthRollDetails {
  readonly criticals: { readonly isNatural1: boolean; readonly isNatural20: boolean } | undefined
}

export function roll(input?: {
  modifier?: number
  rollingWith?: 'Advantage' | 'Disadvantage'
  crit?: boolean
}): GameRollResult<FifthRollResult, FifthRollDetails, RollRecord> {
  if (input?.modifier !== undefined && typeof input?.modifier === 'number')
    validateFinite(input?.modifier, '5E modifier')
  if (input?.modifier !== undefined && typeof input?.modifier === 'number')
    validateRange(input?.modifier, -30, 30, '5E modifier')
  if (
    input?.rollingWith !== undefined &&
    !['Advantage', 'Disadvantage'].includes(input?.rollingWith as string)
  )
    throw new SchemaError(
      `Invalid rollingWith value: ${String(input?.rollingWith)}. Must be 'Advantage' or 'Disadvantage'.`,
      'INVALID_INPUT_TYPE'
    )
  if (input?.rollingWith === 'Advantage') {
    const r = executeRoll({
      sides: 20,
      quantity: 2,
      modifiers: { keep: { highest: 1 }, plus: input?.modifier ?? 0 }
    })
    const total = r.total
    const details = {
      criticals:
        input?.crit !== undefined
          ? { isNatural1: r.rolls[0]?.rolls[0] === 1, isNatural20: r.rolls[0]?.rolls[0] === 20 }
          : undefined
    }
    return { total, result: total, rolls: r.rolls, details }
  }
  if (input?.rollingWith === 'Disadvantage') {
    const r = executeRoll({
      sides: 20,
      quantity: 2,
      modifiers: { keep: { lowest: 1 }, plus: input?.modifier ?? 0 }
    })
    const total = r.total
    const details = {
      criticals:
        input?.crit !== undefined
          ? { isNatural1: r.rolls[0]?.rolls[0] === 1, isNatural20: r.rolls[0]?.rolls[0] === 20 }
          : undefined
    }
    return { total, result: total, rolls: r.rolls, details }
  }
  const r = executeRoll({ sides: 20, quantity: 1, modifiers: { plus: input?.modifier ?? 0 } })
  const total = r.total
  const details = {
    criticals:
      input?.crit !== undefined
        ? { isNatural1: r.rolls[0]?.rolls[0] === 1, isNatural20: r.rolls[0]?.rolls[0] === 20 }
        : undefined
  }
  return { total, result: total, rolls: r.rolls, details }
}

export { SchemaError }
export type { GameRollResult, RollRecord, SchemaErrorCode }
