/* eslint-disable */
// Auto-generated from Powered by the Apocalypse spec. Run `bun run codegen` to regenerate.
// Do not edit this file manually.
import { roll as executeRoll } from '@randsum/roller/roll'
import { validateFinite, validateRange } from '@randsum/roller/validate'
import type { RollRecord } from '@randsum/roller/types'
import type { GameRollResult } from './types'
import { SchemaError } from './lib/errors'
import type { SchemaErrorCode } from './lib/errors'

export type PbtaRollResult = 'miss' | 'strong_hit' | 'weak_hit'

export interface PbtaRollDetails {
  readonly stat: number
  readonly forward: number
  readonly ongoing: number
  readonly diceTotal: number
}

export function roll(input: {
  stat: number
  forward?: number
  ongoing?: number
  rollingWith?: 'Advantage' | 'Disadvantage'
}): GameRollResult<PbtaRollResult, PbtaRollDetails, RollRecord> {
  if (typeof input.stat === 'number') validateFinite(input.stat, 'Powered by the Apocalypse stat')
  if (typeof input.stat === 'number')
    validateRange(input.stat, -3, 5, 'Powered by the Apocalypse stat')
  if (input.forward !== undefined && typeof input.forward === 'number')
    validateFinite(input.forward, 'Powered by the Apocalypse forward')
  if (input.forward !== undefined && typeof input.forward === 'number')
    validateRange(input.forward, -5, 5, 'Powered by the Apocalypse forward')
  if (input.ongoing !== undefined && typeof input.ongoing === 'number')
    validateFinite(input.ongoing, 'Powered by the Apocalypse ongoing')
  if (input.ongoing !== undefined && typeof input.ongoing === 'number')
    validateRange(input.ongoing, -5, 5, 'Powered by the Apocalypse ongoing')
  if (
    input.rollingWith !== undefined &&
    !['Advantage', 'Disadvantage'].includes(input.rollingWith as string)
  )
    throw new SchemaError(
      'INVALID_INPUT_TYPE',
      `Invalid rollingWith value: ${String(input.rollingWith)}. Must be 'Advantage' or 'Disadvantage'.`
    )
  if (input.rollingWith === 'Advantage') {
    const r = executeRoll({
      sides: 6,
      quantity: 3,
      modifiers: {
        keep: { highest: 2 },
        plus: input.stat + (input.forward ?? 0) + (input.ongoing ?? 0)
      }
    })
    const diceTotal = r.rolls.flatMap(x => x.rolls).reduce((a, b) => a + b, 0)
    const total = r.total
    const details = {
      stat: input.stat,
      forward: input.forward ?? 0,
      ongoing: input.ongoing ?? 0,
      diceTotal: diceTotal
    }
    if (total >= 10 && total <= 27) return { total, result: 'strong_hit', rolls: r.rolls, details }
    if (total >= 7 && total <= 9) return { total, result: 'weak_hit', rolls: r.rolls, details }
    if (total >= -11 && total <= 6) return { total, result: 'miss', rolls: r.rolls, details }
    throw new SchemaError('NO_TABLE_MATCH', `No table entry matches total ${total}`)
  }
  if (input.rollingWith === 'Disadvantage') {
    const r = executeRoll({
      sides: 6,
      quantity: 3,
      modifiers: {
        keep: { lowest: 2 },
        plus: input.stat + (input.forward ?? 0) + (input.ongoing ?? 0)
      }
    })
    const diceTotal = r.rolls.flatMap(x => x.rolls).reduce((a, b) => a + b, 0)
    const total = r.total
    const details = {
      stat: input.stat,
      forward: input.forward ?? 0,
      ongoing: input.ongoing ?? 0,
      diceTotal: diceTotal
    }
    if (total >= 10 && total <= 27) return { total, result: 'strong_hit', rolls: r.rolls, details }
    if (total >= 7 && total <= 9) return { total, result: 'weak_hit', rolls: r.rolls, details }
    if (total >= -11 && total <= 6) return { total, result: 'miss', rolls: r.rolls, details }
    throw new SchemaError('NO_TABLE_MATCH', `No table entry matches total ${total}`)
  }
  const r = executeRoll({
    sides: 6,
    quantity: 2,
    modifiers: { plus: input.stat + (input.forward ?? 0) + (input.ongoing ?? 0) }
  })
  const diceTotal = r.rolls.flatMap(x => x.rolls).reduce((a, b) => a + b, 0)
  const total = r.total
  const details = {
    stat: input.stat,
    forward: input.forward ?? 0,
    ongoing: input.ongoing ?? 0,
    diceTotal: diceTotal
  }
  if (total >= 10 && total <= 27) return { total, result: 'strong_hit', rolls: r.rolls, details }
  if (total >= 7 && total <= 9) return { total, result: 'weak_hit', rolls: r.rolls, details }
  if (total >= -11 && total <= 6) return { total, result: 'miss', rolls: r.rolls, details }
  throw new SchemaError('NO_TABLE_MATCH', `No table entry matches total ${total}`)
}

export { SchemaError }
export type { GameRollResult, RollRecord, SchemaErrorCode }
