// Auto-generated from Root RPG spec. Run `bun run codegen` to regenerate.
// Do not edit this file manually.
import { roll as executeRoll } from '@randsum/roller/roll'
import { validateFinite, validateRange } from '@randsum/roller/validate'
import type { RollRecord } from '@randsum/roller'
import type { GameRollResult } from './types'
import { SchemaError } from './lib/errors'
import type { SchemaErrorCode } from './lib/errors'

export type RootRpgRollResult = 'miss' | 'strong_hit' | 'weak_hit'

export function roll(input: {
  bonus: number
  rollingWith?: 'Advantage' | 'Disadvantage'
}): GameRollResult<RootRpgRollResult, undefined, RollRecord> {
  if (typeof input.bonus === 'number') validateFinite(input.bonus, 'Root RPG bonus')
  if (typeof input.bonus === 'number') validateRange(input.bonus, -3, 5, 'Root RPG bonus')
  if (
    input.rollingWith !== undefined &&
    !['Advantage', 'Disadvantage'].includes(input.rollingWith as string)
  )
    throw new SchemaError(
      `Invalid rollingWith value: ${String(input.rollingWith)}. Must be 'Advantage' or 'Disadvantage'.`,
      'INVALID_INPUT_TYPE'
    )
  if (input.rollingWith === 'Advantage') {
    const r = executeRoll({
      sides: 6,
      quantity: 3,
      modifiers: { keep: { highest: 2 }, plus: input.bonus }
    })
    const total = r.total
    if (total >= 10) return { total, result: 'strong_hit', rolls: r.rolls }
    if (total >= 7 && total <= 9) return { total, result: 'weak_hit', rolls: r.rolls }
    if (total <= 6) return { total, result: 'miss', rolls: r.rolls }
    throw new SchemaError(`No table entry matches total ${total}`, 'NO_TABLE_MATCH')
  }
  if (input.rollingWith === 'Disadvantage') {
    const r = executeRoll({
      sides: 6,
      quantity: 3,
      modifiers: { keep: { lowest: 2 }, plus: input.bonus }
    })
    const total = r.total
    if (total >= 10) return { total, result: 'strong_hit', rolls: r.rolls }
    if (total >= 7 && total <= 9) return { total, result: 'weak_hit', rolls: r.rolls }
    if (total <= 6) return { total, result: 'miss', rolls: r.rolls }
    throw new SchemaError(`No table entry matches total ${total}`, 'NO_TABLE_MATCH')
  }
  const r = executeRoll({ sides: 6, quantity: 2, modifiers: { plus: input.bonus } })
  const total = r.total
  if (total >= 10) return { total, result: 'strong_hit', rolls: r.rolls }
  if (total >= 7 && total <= 9) return { total, result: 'weak_hit', rolls: r.rolls }
  if (total <= 6) return { total, result: 'miss', rolls: r.rolls }
  throw new SchemaError(`No table entry matches total ${total}`, 'NO_TABLE_MATCH')
}

export { SchemaError }
export type { GameRollResult, RollRecord, SchemaErrorCode }
