/* eslint-disable */
// Auto-generated from Root RPG spec. Run `bun run codegen` to regenerate.
// Do not edit this file manually.
import { roll as executeRoll, validateFinite, validateRange } from '@randsum/roller'
import type { RollRecord } from '@randsum/roller'
import type { GameRollResult } from './types'

export type RollResult = 'Miss' | 'Strong Hit' | 'Weak Hit'

export function roll(bonus: number): GameRollResult<RollResult, undefined, RollRecord>
export function roll(input: { bonus: number }): GameRollResult<RollResult, undefined, RollRecord>
export function roll(
  rawInput: number | { bonus: number }
): GameRollResult<RollResult, undefined, RollRecord> {
  const input: { bonus: number } = typeof rawInput === 'number' ? { bonus: rawInput } : rawInput
  if (typeof input.bonus === 'number') validateFinite(input.bonus, 'Root RPG bonus')
  if (typeof input.bonus === 'number') validateRange(input.bonus, -20, 20, 'Root RPG bonus')
  const r = executeRoll({ sides: 6, quantity: 2, modifiers: { plus: input.bonus } })
  const total = r.total
  if (total >= 10 && total <= 32) return { total, result: 'Strong Hit', rolls: r.rolls }
  if (total >= 7 && total <= 9) return { total, result: 'Weak Hit', rolls: r.rolls }
  if (total >= -18 && total <= 6) return { total, result: 'Miss', rolls: r.rolls }
  throw new Error(`No table match for total ${total}`)
}

export type { GameRollResult, RollRecord }
