export { matchesComparison } from './matchesComparison'
export { formatComparisonDescription } from './formatComparisonDescription'
export { formatComparisonNotation } from './formatComparisonNotation'
export { formatHumanList } from './formatHumanList'
export { parseComparisonNotation } from './parseComparisonNotation'
export { applyCap } from '../modifiers/apply'
