name: Bundlewatch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Check Bundle Size w/BundleWatch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONALACCESSTOKEN }}

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install Yarn Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: "install --ignore-engines --ignore-scripts"

      - name: Check Bundle Size
        uses: jackyef/bundlewatch-gh-action@0.2.0
        with:
          build-script: yarn build
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
