name: Bundlewatch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Check Bundle Size w/BundleWatch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - run: yarn install --ignore-engines --ignore-scripts

      - name: Check Bundle Size
        uses: jackyef/bundlewatch-gh-action@0.2.0
        with:
          build-script: yarn build
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
