name: CI
on:
  workflow_call:
    inputs:
      package:
        description: 'Package to test'
        required: true
        type: string


jobs:
  build:
    defaults:
      run:
        working-directory: packages/@randsum/${{ inputs.package }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: core
        working-directory: packages/@randsum/core
        run: bun install && bun run build

      - name: notation
        working-directory: packages/@randsum/notation
        run: bun install && bun run build

      - name: dice
        working-directory: packages/@randsum/dice
        run: bun install && bun run build

      - name: roller
        working-directory: packages/@randsum/roller
        run: bun install && bun run build

      - name: customdice
        working-directory: packages/@randsum/customdice
        run: bun install && bun run build

      - name: Test
        run:
          CI=true bun test
