name: CI
on:
  workflow_call:
    inputs:
      package:
        description: 'Package to test'
        required: true
        type: string


jobs:
  test:
    defaults:
      run:
        working-directory: '@randsum/${{ inputs.package }}'

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            changesInPackage:
              - '@randsum/${{ inputs.package }}/**'

      - name: Use Bun
        if: steps.changes.outputs.changesInPackage == 'true'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Run the build script to build sibling packages
      - name: core
        if: steps.changes.outputs.changesInPackage == 'true'
        working-directory: '@randsum/core'
        run: bun install && bun run build

      - name: notation
        if: steps.changes.outputs.changesInPackage == 'true'
        working-directory: '@randsum/notation'
        run: bun install && bun run build

      - name: dice
        if: steps.changes.outputs.changesInPackage == 'true'
        working-directory: '@randsum/dice'
        run: bun install && bun run build

      - name: tower
        if: steps.changes.outputs.changesInPackage == 'true'
        working-directory: '@randsum/tower'
        run: bun install && bun run build

      - name: customdice
        if: steps.changes.outputs.changesInPackage == 'true'
        working-directory: '@randsum/customdice'
        run: bun install && bun run build

      - name: Type Check
        if: steps.changes.outputs.changesInPackage == 'true'
        run: bun ts:check

      - name: Lint & Format
        if: steps.changes.outputs.changesInPackage == 'true'
        run: bun lint && bun format

      - name: Test
        if: steps.changes.outputs.changesInPackage == 'true'
        run:
          CI=true bun test
