name: CI
on: [push]
jobs:
  example_matrix_strategy:
    uses: RANDSUM/randsum/.github/workflows/ci-template.yml@main
    with:
      package: ${{ matrix.package }}
    strategy:
      matrix:
        package: [core, customdice, dice, notation, tower]
