name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONALACCESSTOKEN }}

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install Yarn Dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: "install --ignore-engines --ignore-scripts"

      - name: Run Tests
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: "test:ci"

      - name: Code Cov
        uses: codecov/codecov-action@v2.1.0

      - name: Run Linters
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint

      - name: Check Bundle Size
        uses: jackyef/bundlewatch-gh-action@0.2.0
        with:
          build-script: yarn build
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}

      - name: Build Docs
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: docs

      - name: Commit Docs
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
        with:
          add: 'docs'
          message: '📄 Updating Docs 📄'
          pull: 'NO-PULL'
          push: '--no-verify'
          default_author: github_actions
