name: Docs

on:
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Build Docs
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17

      - name: Install Node.js dependencies
        run: yarn

      - name: Generate Docs
        run: yarn docs

      - name: Add Docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '--no-verify'
          commit_message: 'Generating Docs 📚'
