name: Docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        token: ${{ secrets.PERSONALACCESSTOKEN }} #ensure CI always runs

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - run: yarn install

      - name: Build Docs
        run: yarn docs

      - name: Commit Docs
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs'
          message: '📄 Updating Docs 📄'
          pull: 'NO-PULL'
          push: '--no-verify'
          default_author: github_actions
