name: HealthCheck
on: [push]
jobs:
  build:
    name: Typecheck, Lint, Format

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      - name: TypeCheck
        run: bun ts:check

      - name: Lint
        run: bun lint && bun format
